version: "3.3"

services:
  fastapi:
    build: .
    container_name: fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --reload --port 80
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:8.0.19
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rapid
      MYSQL_DATABASE: rapid_data_hub
    volumes:
      - /opt/persist/mysql/data:/var/lib/mysql
