"""first commit

Revision ID: f0866df2aa95
Revises: 
Create Date: 2021-10-18 15:29:47.429720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0866df2aa95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('organization', sa.String(length=256), nullable=True),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_organization'), 'user', ['organization'], unique=False)
    op.create_table('bucket',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket_name', sa.String(length=256), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=256), nullable=False),
    sa.Column('data_type', sa.String(length=256), nullable=True),
    sa.Column('units', sa.JSON(), nullable=True),
    sa.Column('original_file_name', sa.String(length=256), nullable=True),
    sa.Column('added_by', sa.String(length=256), nullable=True),
    sa.Column('num_of_rows', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.JSON(), nullable=True),
    sa.Column('additional_information', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_added_by'), 'table', ['added_by'], unique=False)
    op.create_index(op.f('ix_table_original_file_name'), 'table', ['original_file_name'], unique=False)
    op.create_index(op.f('ix_table_table_name'), 'table', ['table_name'], unique=True)
    op.create_table('bucketmetadata',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bucket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['bucket.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_bucket_relation',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bucket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['bucket.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    op.create_table('user_table_relation',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_table_relation')
    op.drop_table('user_bucket_relation')
    op.drop_table('bucketmetadata')
    op.drop_index(op.f('ix_table_table_name'), table_name='table')
    op.drop_index(op.f('ix_table_original_file_name'), table_name='table')
    op.drop_index(op.f('ix_table_added_by'), table_name='table')
    op.drop_table('table')
    op.drop_table('bucket')
    op.drop_index(op.f('ix_user_organization'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
